// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(grunt) {
    grunt.loadNpmTasks('grunt-coffee');
    grunt.initConfig({
      lint: {
        files: ['*.js', '*.json', 'lib/*.js']
      },
      jshint: {
        options: {
          curly: false,
          newcap: false,
          shadow: true,
          undef: true,
          eqeqeq: true,
          immed: true,
          latedef: true,
          noarg: true,
          sub: true,
          boss: true,
          eqnull: true,
          node: true,
          strict: false
        }
      },
      coffee: {
        app: {
          src: ['src/*.coffee'],
          dest: 'lib'
        }
      },
      watch: {
        files: ["*.js", "*.json", "src/*.coffee", "test/*.coffee"],
        tasks: "coffee lint"
      }
    });
    return grunt.registerTask('default', 'coffee');
  };

}).call(this);
