// Generated by CoffeeScript 1.4.0
(function() {
  var Admin, admin, admins, _i, _len;

  Admin = require('icecast-admin').Admin;

  admins = [];

  admins.push(new Admin({
    url: 'http://username:password@hostname:port/'
  }));

  admins.push(new Admin({
    hostname: 'hostname',
    port: 'port',
    username: 'username',
    password: 'port'
  }));

  admins.push(new Admin({
    host: 'hostname',
    password: 'password'
  }));

  admins.push(new Admin({
    hostname: 'hostname',
    password: 'password'
  }));

  admins.push(new Admin({
    host: 'hostname:port',
    password: 'password'
  }));

  for (_i = 0, _len = admins.length; _i < _len; _i++) {
    admin = admins[_i];
    console.log('');
    console.log(admin.options);
  }

}).call(this);
