// Generated by CoffeeScript 1.4.0
(function() {
  var Admin, admin;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Admin = require('..').Admin;

  admin = new Admin({
    url: process.argv[2]
  });

  admin.getStats(function(result) {
    var source, _i, _len, _ref, _results;
    console.log('result', result);
    console.log("" + result.icestats.source.length + " sources");
    _ref = result.icestats.source;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      source = _ref[_i];
      _results.push(console.log(source));
    }
    return _results;
  });

}).call(this);
