// Generated by CoffeeScript 1.4.0
(function() {
  var Admin, admin;

  Admin = require('..').Admin;

  admin = new Admin({
    host: 'ted.onouo.com',
    port: 8000,
    password: 'ia6MuiCh'
  });

  admin.getStats(function(result) {
    return console.log('result', result);
  });

}).call(this);
