// Generated by CoffeeScript 1.4.0
(function() {
  var Admin, admin;

  Admin = require('..').Admin;

  admin = new Admin({
    host: 'ted.onouo.com',
    port: 8000,
    password: 'ia6MuiCh'
  });

  admin.getStats(function(err, result) {
    if (err) {
      return console.log("Error:", err);
    } else {
      return console.log('result', result);
    }
  });

}).call(this);
