// Generated by CoffeeScript 1.6.2
(function() {
  var Admin, admin;

  process.stdout.write('\u001B[2J\u001B[0;0f');

  Admin = require('icecast-admin').Admin;

  if (process.argv.length < 4) {
    console.log("usage: " + process.argv[1] + " 'http://username:password@hostname:port/' '/mountpoint'");
    process.exit(1);
  }

  admin = new Admin({
    url: process.argv[2]
  });

  admin.listClients(process.argv[3], function(err, result) {
    var listener, source, _i, _len, _ref, _results;

    if (err) {
      return console.log('Error:', err);
    } else {
      source = result.icestats.source[0];
      console.log("Listeners: " + source.Listeners);
      _ref = source.listener;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        listener = _ref[_i];
        _results.push(console.log("ID=" + listener.ID + ", IP=" + listener.IP + ", Connected=" + listener.Connected + ", UserAgent=" + listener.UserAgent));
      }
      return _results;
    }
  });

}).call(this);
