// Generated by CoffeeScript 1.6.2
(function() {
  var Admin, admin;

  Admin = require('icecast-admin').Admin;

  admin = new Admin({
    host: 'localhost',
    port: 8000,
    password: 'hackme'
  });

  admin.stats(function(err, result) {
    if (err) {
      return console.log('Error:', err);
    } else {
      return console.log('result', result);
    }
  });

}).call(this);
